name: security operations
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    name: NodeGoat Security Pipeline
    steps:
      - uses: actions/checkout@v3
      - name: Installing node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install
      - name: Black Duck Scan
        env:
          BRIDGE_BLACKDUCK_URL: ${{ vars.BLACKDUCK_URL }}
          BRIDGE_BLACKDUCK_TOKEN: ${{ secrets.BLACKDUCK_TOKEN }}
          BRIDGE_GITHUB_USER_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRIDGE_GITHUB_REPOSITORY_OWNER_NAME: ${{ github.repository_owner }}
          BRIDGE_GITHUB_REPOSITORY_NAME: ${{ github.event.repository.name }}
          BRIDGE_GITHUB_REPOSITORY_BRANCH_NAME: ${{ github.ref_name }}
        run: |
          curl -fLsS -o bridge.zip ${{ vars.BRIDGECLI_LINUX64 }} && unzip -qo -d ${{ runner.temp }} bridge.zip && rm -f bridge.zip
          ${{ runner.temp }}/synopsys-bridge --stage blackduck \
            blackduck.scan.full='true' \
            blackduck.scan.failure.severities='BLOCKER' \
            blackduck.fixpr.enabled='true' \
            blackduck.reports.sarif.create='true'
