name: security operations
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    name: NodeGoat
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install
