name: security operations
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    name: NodeGoat Security Pipeline
    steps:
      - uses: actions/checkout@v3
      - name: Installing node
        env:
          BRIDGE_POLARIS_SERVERURL: ${{ secrets.POLARIS_SERVERURL }}
          BRIDGE_POLARIS_ACCESSTOKEN: ${{ secrets.POLARIS_ACCESSTOKEN }}
          BRIDGE_POLARIS_ASSESSMENT_TYPES: 'SAST'
          BRIDGE_POLARIS_APPLICATION_NAME: 'JP-NodeGoat'
          BRIDGE_POLARIS_PROJECT_NAME: 'NodeGoat'
          BRIDGE_POLARIS_BRANCH_NAME: ${{ github.event.ref_name }}
          BRIDGE_DOWNLOAD: ${{ secrets.BRIDGECLI_LINUX64 }}        
          BRIDGE_BLACKDUCK_URL: ${{ secrets.BRIDGE_BLACKDUCK_URL }}
          BRIDGE_BLACKDUCK_TOKEN: ${{ secrets.BRIDGE_BLACKDUCK_TOKEN }}
          BRIDGE_GITHUB_USER_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRIDGE_GITHUB_REPOSITORY_OWNER_NAME: ${{ github.repository_owner }}
          BRIDGE_GITHUB_REPOSITORY_NAME: ${{ github.event.repository.name }}
          BRIDGE_GITHUB_REPOSITORY_BRANCH_NAME: ${{ github.ref_name }}      
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install
      - name: Black Duck Scan
        shell: bash
        run: |
          curl -fLsS -o bridge.zip $BRIDGE_DOWNLOAD && unzip -qo -d ${{ runner.temp }} bridge.zip && rm -f bridge.zip
          ${{ runner.temp }}/synopsys-bridge --stage blackduck \
            blackduck.scan.full='true' \
            blackduck.scan.failure.severities='BLOCKER' \
            blackduck.fixpr.enabled='false' \
            blackduck.reports.sarif.create='false'
      - name: Polaris Scan
        shell: bash
        run: |
          ${{ runner.temp }}/synopsys-bridge --stage polaris polaris.project.name=$BRIDGE_POLARIS_PROJECT_NAME \
          polaris.branch.name=$BRIDGE_GITHUB_REPOSITORY_BRANCH_NAME \
          polaris.application.name=$BRIDGE_POLARIS_APPLICATION_NAME \
          polaris.assessment.types=$BRIDGE_POLARIS_ASSESSMENT_TYPES \
          polaris.serverurl=$BRIDGE_POLARIS_SERVERURL \
